export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Quote } from "./Quote";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Projects } from "./Projects";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as SocialMedia } from "./SocialMedia";